/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsetRouteImport } from './routes/aset'
import { Route as KamarRouteImport } from './routes/kamar'
import { Route as KeuanganRouteImport } from './routes/keuangan'
import { Route as LainnyaRouteImport } from './routes/lainnya'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsetRoute = AsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarRoute = KamarRouteImport.update({
  id: '/kamar',
  path: '/kamar',
  getParentRoute: () => rootRouteImport,
} as any)
const KeuanganRoute = KeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const LainnyaRoute = LainnyaRouteImport.update({
  id: '/lainnya',
  path: '/lainnya',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aset': typeof AsetRoute
  '/kamar': typeof KamarRoute
  '/keuangan': typeof KeuanganRoute
  '/lainnya': typeof LainnyaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aset': typeof AsetRoute
  '/kamar': typeof KamarRoute
  '/keuangan': typeof KeuanganRoute
  '/lainnya': typeof LainnyaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aset': typeof AsetRoute
  '/kamar': typeof KamarRoute
  '/keuangan': typeof KeuanganRoute
  '/lainnya': typeof LainnyaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aset' | '/kamar' | '/keuangan' | '/lainnya'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aset' | '/kamar' | '/keuangan' | '/lainnya'
  id: '__root__' | '/' | '/aset' | '/kamar' | '/keuangan' | '/lainnya'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsetRoute: typeof AsetRoute
  KamarRoute: typeof KamarRoute
  KeuanganRoute: typeof KeuanganRoute
  LainnyaRoute: typeof LainnyaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aset': {
      id: '/aset'
      path: '/aset'
      fullPath: '/aset'
      preLoaderRoute: typeof AsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar': {
      id: '/kamar'
      path: '/kamar'
      fullPath: '/kamar'
      preLoaderRoute: typeof KamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keuangan': {
      id: '/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof KeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lainnya': {
      id: '/lainnya'
      path: '/lainnya'
      fullPath: '/lainnya'
      preLoaderRoute: typeof LainnyaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsetRoute: AsetRoute,
  KamarRoute: KamarRoute,
  KeuanganRoute: KeuanganRoute,
  LainnyaRoute: LainnyaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
